// Netlify build step. (1) Stamps script and stylesheet URLs with the commit hash so
// browsers never reuse an old file. (2) Writes the site's <head> metadata, robots.txt
// and llms.txt from the brand and locale environment variables.
import fs from "node:fs";
import { siteMeta, siteJsonLd, applyHead } from "../netlify/lib/seo.mjs";

const file = new URL("../public/index.html", import.meta.url);
const v = (process.env.COMMIT_REF || String(Date.now())).slice(0, 10);
let html = fs.readFileSync(file, "utf8");
html = html.replace(/(href|src)="(\/[^"?]+\.(?:js|css))(?:\?v=[^"]*)?"/g, (m, attr, path) => `${attr}="${path}?v=${v}"`);

const m = siteMeta();
html = applyHead(html, { title: m.title, description: m.description, canonical: `${m.url}/`, lang: m.lang, jsonLd: siteJsonLd(m), ogImage: m.ogImage });
html = html.replace(/<link rel="icon"[^>]*>/, `<link rel="icon" type="image/png" href="${m.brand.favicon}">`).replace(/<link rel="apple-touch-icon"[^>]*>/, `<link rel="apple-touch-icon" href="${m.brand.touchIcon}">`);
fs.writeFileSync(file, html);

fs.writeFileSync(new URL("../public/robots.txt", import.meta.url), `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /.netlify/\n\nSitemap: ${m.url}/sitemap.xml\n`);

const faq = {
  ja: [["何ができますか？", "米国上場企業のティッカーを入力すると、業績・財務・バリュエーション・テクニカル・株主・役員を1ページで表示し、決算説明会のトランスクリプトと最新ニュースをAIが要約した長期トレンド、直近動向、この1年のストーリー、強気・弱気シナリオ、深掘り分析を読めます。"], ["データの出所は？", "SEC EDGARに公開された財務情報、決算説明会のトランスクリプト、Financial Modeling Prepの市場データ。AI要約はAnthropicのClaudeが生成します。"], ["料金は？", "月額US$10（現地通貨換算）。7日間の無料トライアルがあり、いつでも解約できます。"], ["誰が作りましたか？", "元フィデリティ投信 調査部長で、2017年に独立した個人投資家のポール・サイ（Paul Tsai）です。"]],
  en: [["What does it do?", "Type a US ticker and get results, financials, valuation, a technical read, holders and officers on one page, plus AI digests of the earnings-call transcripts and news: long-term trend, recent quarters, the past year's story, bull and bear cases, and a deep-dive analysis."], ["Where does the data come from?", "Public financials filed with SEC EDGAR, earnings-call transcripts, and market data from Financial Modeling Prep. The AI text is generated by Anthropic's Claude."], ["What does it cost?", "US$10 a month, shown in your local currency, with a 7-day free trial and cancellation at any time."], ["Who built it?", "Paul Tsai, former head of research at Fidelity Investments Japan and an independent investor since 2017."]],
  "zh-TW": [["它能做什麼？", "輸入美股代號，一頁看完業績、財務、估值、技術面、股東與經營層，並閱讀 AI 依財報電話會議逐字稿與新聞整理的長期趨勢、近期動態、過去一年的故事、多空論點與深度分析。"], ["資料來源？", "SEC EDGAR 公開財務資料、財報電話會議逐字稿，以及 Financial Modeling Prep 的市場數據。AI 文字由 Anthropic 的 Claude 產生。"], ["費用？", "每月 US$10（以當地貨幣計價），免費試用 7 天，隨時可取消。"], ["誰做的？", "前富達投信研究部主管、2017 年起成為獨立投資人的 Paul Tsai（蔡）。"]],
}[m.locale] || [];
fs.writeFileSync(new URL("../public/llms.txt", import.meta.url), `# ${m.brand.name}\n\n> ${m.description}\n\nURL: ${m.url}\nLanguages: ${m.locales.join(", ")}\nPrice: ${m.price} per month, 7-day free trial\nCreator: Paul Tsai (https://paultsai.net), former head of research at Fidelity Investments Japan\nMethod: the deep dives and sector reports apply the Paul Tsai Company Research Specification (966 lines, about 17,000 words, 14 research modules; three independent findings, reproducible DCF and reverse-DCF conventions, no recommendations)\n\n## What a ticker page contains\n\n- Overview: profile, revenue mix, the past year's story, long-term trend, recent quarters, bull case, bear case, competitors, index membership and weights\n- Results and financials: 5 fiscal years plus consensus estimates and recent quarters, dividends, cash flow, balance sheet and leverage\n- Valuation: target-price calculator, all current multiples and yields, a reference DCF\n- Technical: AI reading of the chart with support and resistance bands, 50- and 200-day averages\n- Holders and management: institutional holders, officers, splits\n- Deep dive: business quality, trajectory and market expectations with supporting analysis\n\n## Public pages\n\n- ${m.url}/ : landing page with a live sample\n- ${m.url}/s/AAPL : example ticker page (public preview; full page for subscribers)\n- ${m.url}/sitemap.xml\n\n## FAQ\n\n${faq.map(([q, a]) => `Q: ${q}\nA: ${a}`).join("\n\n")}\n`);
console.log(`stamped assets with v=${v}; head for ${m.brand.name} (${m.locale}); robots.txt and llms.txt written`);
